<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Benjamin Frizzell">
<meta name="author" content="Hankun Xiao">
<meta name="author" content="Essie Zhang">
<meta name="author" content="Mason Zhang">
<meta name="dcterms.date" content="2024-12-16">

<title>Mushroom Edibility Classification Using Feature-Based Machine Learning Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="mushroom_classifier_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="mushroom_classifier_report_files/libs/quarto-html/quarto.js"></script>
<script src="mushroom_classifier_report_files/libs/quarto-html/popper.min.js"></script>
<script src="mushroom_classifier_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="mushroom_classifier_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="mushroom_classifier_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="mushroom_classifier_report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="mushroom_classifier_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="mushroom_classifier_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="mushroom_classifier_report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory data analysis</a></li>
  <li><a href="#result-discussion" id="toc-result-discussion" class="nav-link" data-scroll-target="#result-discussion">Result &amp; Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="../mushroom_classifier_report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mushroom Edibility Classification Using Feature-Based Machine Learning Approach</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Benjamin Frizzell </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            UBC Master of Data Science
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Hankun Xiao </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            UBC Master of Data Science
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Essie Zhang </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            UBC Master of Data Science
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Mason Zhang </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            UBC Master of Data Science
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 16, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>In this project, we developed and evaluated a machine learning model to classify mushroom edibility (i.e., whether they are edible or poisonous) based on features such as color, habitat, and structure. This is an important task as eating poisonous mushrooms can lead to severe health risks, while identifying toxic mushrooms through manual visual inspection can be challenging and time-consuming.</p>
<p>We built and fine-tuned a Support Vector Classifier (SVC), using both accuracy and <span class="math inline">\(F_{\beta}\)</span> as performance metrics. The <span class="math inline">\(F_{\beta}\)</span> score is a weighted harmonic mean of precision and recall. We calculated <span class="math inline">\(F_{\beta}\)</span> with <span class="math inline">\(\beta = 2\)</span> to place greater emphasis on recall, as predicting a poisonous mushroom as edible (false negatives) could have severe consequences. Our final model achieved an overall accuracy of 0.996 and <span class="math inline">\(F_{\beta}\)</span> score with <span class="math inline">\(\beta = 2\)</span> of 0.997 with 12134 correct predictions out of 12181 test observations. In terms of error, the model predicted 22 poisonous mushrooms as edible (false negative) and predicted 25 edible mushrooms as poisonous (false positive).</p>
<p>Even though the model shows promising performance, a limitation of this project is the lack of incorporation of biological domain knowledge about mushrooms into the feature engineering process, which could further reduce false negatives. This is an area that could be addressed in future work.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Mushrooms are a widely consumed food source known for their rich nutritional content, including essential vitamins and minerals. However, not all mushrooms are safe for consumption, as many species are highly toxic. Eating poisonous mushrooms can lead to severe health consequences, including hospitalization and death, as highlighted in an incident report from <span class="citation" data-cites="cdc2024">Disease Control and (CDC) (<a href="#ref-cdc2024" role="doc-biblioref">2024</a>)</span>.</p>
<p>Distinguishing between edible and poisonous mushrooms is particularly challenging, especially when dealing with large quantities. According to research by <span class="citation" data-cites="niosh2019">Occupational Safety and (NIOSH) (<a href="#ref-niosh2019" role="doc-biblioref">2019</a>)</span>, in the commercial distribution of agricultural products, there is a risk of mixing edible and poisonous mushrooms. Traditional identification methods rely on human expertise, which can be time-consuming and inconsistent.</p>
<p>The primary goal of this project is to develop an accurate machine learning model that minimizes false negatives (i.e., misclassifying poisonous mushrooms as edible) while maintaining reasonable overall performance. To achieve this, our project applies machine learning techniques to classify mushroom edibility based on various features, such as color, habitat, and structure. The dataset used in this study contains detailed observations of mushrooms, categorized as either edible or poisonous <span class="citation" data-cites="secondary_mushroom_848">Wagner and Hattab (<a href="#ref-secondary_mushroom_848" role="doc-biblioref">2021</a>)</span>. Our analysis applied three classification algorithms: Support Vector Classifier (SVC), K-Nearest Neighbors (KNN), and Logistic Regression. These models were chosen for their diverse approaches to classification and their ability to capture complex relationships between features.</p>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>The dataset used in this project is the Secondary Mushroom Dataset <span class="citation" data-cites="secondary_mushroom_848">Wagner and Hattab (<a href="#ref-secondary_mushroom_848" role="doc-biblioref">2021</a>)</span>. This dataset contains 61069 hypothetical mushrooms with caps based on 173 species (353 mushrooms per species). Each mushroom is identified as definitely edible, definitely poisonous, or of unknown edibility and not recommended (the latter class was combined with the poisonous class).</p>
</section>
<section id="analysis" class="level3">
<h3 class="anchored" data-anchor-id="analysis">Analysis</h3>
<p>The mushroom dataset is balanced with 55.22% of poisonous mushroom and 44.78% of edible mushroom. All variables were standardized and variables with more than 15% missing values are dropped, because imputing a variable that has a significant proportion of missing data might introduce too much noise or bias, making it unreliable. Data was splitted with 80% being partitioned into the training set and 20% being partitioned into the test set. Three classification models including Support Vector Classifier (SVC), K-Nearest Neighbors (KNN), and Logistic Regression are used to predict whether a mushroom is edible or poisonous. The fine tuned Support Vector Classifier has the best overall performance. The hyperparameter was chosen using 5-fold cross validation with <span class="math inline">\(F_{\beta}\)</span> score as the classification metric. <span class="math inline">\(\beta\)</span> was chosen to be set to 2 for the <span class="math inline">\(F_{\beta}\)</span> score to increase the weight on recall during fitting because predicting a mushroom to be edible when it is in fact poisonous could have severe health consequences. Therefore the goal is to prioritize the minimization of false negatives. The Python programming language <span class="citation" data-cites="Python">Van Rossum and Drake (<a href="#ref-Python" role="doc-biblioref">2009</a>)</span> and the following Python packages were used to perform the analysis: Matplotlib <span class="citation" data-cites="4160265">Hunter (<a href="#ref-4160265" role="doc-biblioref">2007</a>)</span>), Pandas: <span class="citation" data-cites="mckinney-proc-scipy-2010">McKinney (<a href="#ref-mckinney-proc-scipy-2010" role="doc-biblioref">2010</a>)</span>, Scikit-learn: <span class="citation" data-cites="scikit-learn">Pedregosa et al. (<a href="#ref-scikit-learn" role="doc-biblioref">2011</a>)</span>, NumPy: <span class="citation" data-cites="harris2020array">Harris et al. (<a href="#ref-harris2020array" role="doc-biblioref">2020</a>)</span>, SciPy: <span class="citation" data-cites="2020SciPy-NMeth">Virtanen et al. (<a href="#ref-2020SciPy-NMeth" role="doc-biblioref">2020</a>)</span>, UCIMLRepo: <span class="citation" data-cites="secondary_mushroom_848">Wagner and Hattab (<a href="#ref-secondary_mushroom_848" role="doc-biblioref">2021</a>)</span>., Pandera: <span class="citation" data-cites="niels_bantilan-proc-scipy-2020">Bantilan (<a href="#ref-niels_bantilan-proc-scipy-2020" role="doc-biblioref">2020</a>)</span>, Pytest: <span class="citation" data-cites="pytest8.3.4">Krekel et al. (<a href="#ref-pytest8.3.4" role="doc-biblioref">2004</a>)</span>, and Deepchecks: <span class="citation" data-cites="Chorev_Deepchecks_A_Library_2022">Chorev et al. (<a href="#ref-Chorev_Deepchecks_A_Library_2022" role="doc-biblioref">2022</a>)</span>.</p>
</section>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory data analysis</h2>
<section id="part-1-numeric-features" class="level3">
<h3 class="anchored" data-anchor-id="part-1-numeric-features">Part 1: Numeric Features</h3>
<div id="fig-cap-diameter" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cap-diameter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/cap-diameter_histogram.png" class="img-fluid figure-img" style="width:40.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cap-diameter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The Distribution of Feature Cap Diameter
</figcaption>
</figure>
</div>
<div id="fig-stem-height" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stem-height-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/stem-height_histogram.png" class="img-fluid figure-img" style="width:40.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stem-height-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The Distribution of Feature Stem Height
</figcaption>
</figure>
</div>
<div id="fig-stem-width" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stem-width-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/stem-width_histogram.png" class="img-fluid figure-img" style="width:40.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stem-width-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: The Distribution of Feature Stem Width
</figcaption>
</figure>
</div>
<p>The EDA shows that all numeric columns in the mushroom dataset are nearly normal with some skewness. A robust preprocessing scheme <code>QuantileTransformer</code> is used because it can transform skewed data or heavy-tailed distributions into a more Gaussian-like shape and reduce the impact of outliers. <code>OneHotEncoder</code> is applied for categorical features in the mushroom dataset, because each feature does not contains much categories and they are not ordered. It is critical to keep all important information in the features. Since ring type feature has many missing values, it was filled in with a “Missing” class. Treating missing values as a distinct category provides a way to model the absence of data directly. This can be valuable because missingness itself might carry information; for example, some mushrooms may not have particularly unique ring types that cannot be classified into the other groups, or simply may not have rings at all.</p>
</section>
<section id="part-2-categorical-features" class="level3">
<h3 class="anchored" data-anchor-id="part-2-categorical-features">Part 2: Categorical Features</h3>
<div class="cell" data-execution_count="2">
<div id="tbl-cap-shape" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cap-shape-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: The distribution of cap shape.
</figcaption>
<div aria-describedby="tbl-cap-shape-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<<<<<<< HEAD
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="2">
=======
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="44">
>>>>>>> main
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">cap-shape</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">x</td>
<td style="text-align: right;">21510</td>
<td style="text-align: right;">0.441484</td>
</tr>
<tr class="even">
<td style="text-align: left;">f</td>
<td style="text-align: right;">10698</td>
<td style="text-align: right;">0.219572</td>
</tr>
<tr class="odd">
<td style="text-align: left;">s</td>
<td style="text-align: right;">5717</td>
<td style="text-align: right;">0.117339</td>
</tr>
<tr class="even">
<td style="text-align: left;">b</td>
<td style="text-align: right;">4615</td>
<td style="text-align: right;">0.0947211</td>
</tr>
<tr class="odd">
<td style="text-align: left;">o</td>
<td style="text-align: right;">2634</td>
<td style="text-align: right;">0.0540618</td>
</tr>
<tr class="even">
<td style="text-align: left;">p</td>
<td style="text-align: right;">2098</td>
<td style="text-align: right;">0.0430606</td>
</tr>
<tr class="odd">
<td style="text-align: left;">c</td>
<td style="text-align: right;">1450</td>
<td style="text-align: right;">0.0297607</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="3">
<div id="tbl-cap-color" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cap-color-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: The distribution of mushroom cap colors.
</figcaption>
<div aria-describedby="tbl-cap-color-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<<<<<<< HEAD
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="3">
=======
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="45">
>>>>>>> main
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">cap-color</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">n</td>
<td style="text-align: right;">19407</td>
<td style="text-align: right;">0.398321</td>
</tr>
<tr class="even">
<td style="text-align: left;">y</td>
<td style="text-align: right;">6876</td>
<td style="text-align: right;">0.141127</td>
</tr>
<tr class="odd">
<td style="text-align: left;">w</td>
<td style="text-align: right;">6175</td>
<td style="text-align: right;">0.126739</td>
</tr>
<tr class="even">
<td style="text-align: left;">g</td>
<td style="text-align: right;">3410</td>
<td style="text-align: right;">0.0699889</td>
</tr>
<tr class="odd">
<td style="text-align: left;">e</td>
<td style="text-align: right;">3205</td>
<td style="text-align: right;">0.0657814</td>
</tr>
<tr class="even">
<td style="text-align: left;">o</td>
<td style="text-align: right;">2905</td>
<td style="text-align: right;">0.059624</td>
</tr>
<tr class="odd">
<td style="text-align: left;">r</td>
<td style="text-align: right;">1399</td>
<td style="text-align: right;">0.0287139</td>
</tr>
<tr class="even">
<td style="text-align: left;">u</td>
<td style="text-align: right;">1355</td>
<td style="text-align: right;">0.0278108</td>
</tr>
<tr class="odd">
<td style="text-align: left;">p</td>
<td style="text-align: right;">1332</td>
<td style="text-align: right;">0.0273388</td>
</tr>
<tr class="even">
<td style="text-align: left;">k</td>
<td style="text-align: right;">1016</td>
<td style="text-align: right;">0.020853</td>
</tr>
<tr class="odd">
<td style="text-align: left;">b</td>
<td style="text-align: right;">964</td>
<td style="text-align: right;">0.0197857</td>
</tr>
<tr class="even">
<td style="text-align: left;">l</td>
<td style="text-align: right;">678</td>
<td style="text-align: right;">0.0139157</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="4">
<div id="tbl-does-bruise-or-bleed" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-does-bruise-or-bleed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: The distribution of mushrooms that bruise or bleed.
</figcaption>
<div aria-describedby="tbl-does-bruise-or-bleed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<<<<<<< HEAD
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="4">
=======
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="46">
>>>>>>> main
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">does-bruise-or-bleed</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">f</td>
<td style="text-align: right;">40333</td>
<td style="text-align: right;">0.827819</td>
</tr>
<tr class="even">
<td style="text-align: left;">t</td>
<td style="text-align: right;">8389</td>
<td style="text-align: right;">0.172181</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="5">
<div id="tbl-gill-color" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-gill-color-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: The distribution of mushroom gill colors.
</figcaption>
<div aria-describedby="tbl-gill-color-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<<<<<<< HEAD
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="5">
=======
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="47">
>>>>>>> main
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">gill-color</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">w</td>
<td style="text-align: right;">14836</td>
<td style="text-align: right;">0.304503</td>
</tr>
<tr class="even">
<td style="text-align: left;">n</td>
<td style="text-align: right;">7742</td>
<td style="text-align: right;">0.158902</td>
</tr>
<tr class="odd">
<td style="text-align: left;">y</td>
<td style="text-align: right;">7595</td>
<td style="text-align: right;">0.155884</td>
</tr>
<tr class="even">
<td style="text-align: left;">p</td>
<td style="text-align: right;">4769</td>
<td style="text-align: right;">0.0978819</td>
</tr>
<tr class="odd">
<td style="text-align: left;">g</td>
<td style="text-align: right;">3295</td>
<td style="text-align: right;">0.0676286</td>
</tr>
<tr class="even">
<td style="text-align: left;">f</td>
<td style="text-align: right;">2734</td>
<td style="text-align: right;">0.0561143</td>
</tr>
<tr class="odd">
<td style="text-align: left;">o</td>
<td style="text-align: right;">2312</td>
<td style="text-align: right;">0.0474529</td>
</tr>
<tr class="even">
<td style="text-align: left;">k</td>
<td style="text-align: right;">1908</td>
<td style="text-align: right;">0.039161</td>
</tr>
<tr class="odd">
<td style="text-align: left;">r</td>
<td style="text-align: right;">1131</td>
<td style="text-align: right;">0.0232133</td>
</tr>
<tr class="even">
<td style="text-align: left;">e</td>
<td style="text-align: right;">842</td>
<td style="text-align: right;">0.0172817</td>
</tr>
<tr class="odd">
<td style="text-align: left;">u</td>
<td style="text-align: right;">827</td>
<td style="text-align: right;">0.0169739</td>
</tr>
<tr class="even">
<td style="text-align: left;">b</td>
<td style="text-align: right;">731</td>
<td style="text-align: right;">0.0150035</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="6">
<div id="tbl-stem-color" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stem-color-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: The distribution of mushroom stem colors.
</figcaption>
<div aria-describedby="tbl-stem-color-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<<<<<<< HEAD
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="6">
=======
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="48">
>>>>>>> main
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">stem-color</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">w</td>
<td style="text-align: right;">18377</td>
<td style="text-align: right;">0.377181</td>
</tr>
<tr class="even">
<td style="text-align: left;">n</td>
<td style="text-align: right;">14478</td>
<td style="text-align: right;">0.297155</td>
</tr>
<tr class="odd">
<td style="text-align: left;">y</td>
<td style="text-align: right;">6291</td>
<td style="text-align: right;">0.12912</td>
</tr>
<tr class="even">
<td style="text-align: left;">g</td>
<td style="text-align: right;">2090</td>
<td style="text-align: right;">0.0428964</td>
</tr>
<tr class="odd">
<td style="text-align: left;">o</td>
<td style="text-align: right;">1733</td>
<td style="text-align: right;">0.0355691</td>
</tr>
<tr class="even">
<td style="text-align: left;">e</td>
<td style="text-align: right;">1628</td>
<td style="text-align: right;">0.0334141</td>
</tr>
<tr class="odd">
<td style="text-align: left;">u</td>
<td style="text-align: right;">1189</td>
<td style="text-align: right;">0.0244038</td>
</tr>
<tr class="even">
<td style="text-align: left;">p</td>
<td style="text-align: right;">814</td>
<td style="text-align: right;">0.016707</td>
</tr>
<tr class="odd">
<td style="text-align: left;">f</td>
<td style="text-align: right;">705</td>
<td style="text-align: right;">0.0144698</td>
</tr>
<tr class="even">
<td style="text-align: left;">k</td>
<td style="text-align: right;">676</td>
<td style="text-align: right;">0.0138746</td>
</tr>
<tr class="odd">
<td style="text-align: left;">r</td>
<td style="text-align: right;">420</td>
<td style="text-align: right;">0.00862034</td>
</tr>
<tr class="even">
<td style="text-align: left;">l</td>
<td style="text-align: right;">181</td>
<td style="text-align: right;">0.00371495</td>
</tr>
<tr class="odd">
<td style="text-align: left;">b</td>
<td style="text-align: right;">140</td>
<td style="text-align: right;">0.00287345</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="7">
<div id="tbl-has-ring" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="7">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-has-ring-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: The distribution of samples that have and do not have rings.
</figcaption>
<div aria-describedby="tbl-has-ring-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<<<<<<< HEAD
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="7">
=======
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="49">
>>>>>>> main
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">has-ring</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">f</td>
<td style="text-align: right;">36495</td>
<td style="text-align: right;">0.749046</td>
</tr>
<tr class="even">
<td style="text-align: left;">t</td>
<td style="text-align: right;">12227</td>
<td style="text-align: right;">0.250954</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="8">
<div id="tbl-ring-type" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="8">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ring-type-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: The distribution of mushroom ring types.
</figcaption>
<div aria-describedby="tbl-ring-type-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<<<<<<< HEAD
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="8">
=======
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="50">
>>>>>>> main
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">ring-type</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">f</td>
<td style="text-align: right;">38440</td>
<td style="text-align: right;">0.822827</td>
</tr>
<tr class="even">
<td style="text-align: left;">e</td>
<td style="text-align: right;">1964</td>
<td style="text-align: right;">0.0420404</td>
</tr>
<tr class="odd">
<td style="text-align: left;">z</td>
<td style="text-align: right;">1713</td>
<td style="text-align: right;">0.0366676</td>
</tr>
<tr class="even">
<td style="text-align: left;">l</td>
<td style="text-align: right;">1151</td>
<td style="text-align: right;">0.0246377</td>
</tr>
<tr class="odd">
<td style="text-align: left;">r</td>
<td style="text-align: right;">1129</td>
<td style="text-align: right;">0.0241668</td>
</tr>
<tr class="even">
<td style="text-align: left;">p</td>
<td style="text-align: right;">1028</td>
<td style="text-align: right;">0.0220048</td>
</tr>
<tr class="odd">
<td style="text-align: left;">g</td>
<td style="text-align: right;">1005</td>
<td style="text-align: right;">0.0215125</td>
</tr>
<tr class="even">
<td style="text-align: left;">m</td>
<td style="text-align: right;">287</td>
<td style="text-align: right;">0.00614337</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="9">
<div id="tbl-habitat" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="9">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-habitat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: The distribution of mushroom habitats.
</figcaption>
<div aria-describedby="tbl-habitat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<<<<<<< HEAD
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="9">
=======
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="51">
>>>>>>> main
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">habitat</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">d</td>
<td style="text-align: right;">35162</td>
<td style="text-align: right;">0.721686</td>
</tr>
<tr class="even">
<td style="text-align: left;">g</td>
<td style="text-align: right;">6403</td>
<td style="text-align: right;">0.131419</td>
</tr>
<tr class="odd">
<td style="text-align: left;">l</td>
<td style="text-align: right;">2539</td>
<td style="text-align: right;">0.052112</td>
</tr>
<tr class="even">
<td style="text-align: left;">m</td>
<td style="text-align: right;">2344</td>
<td style="text-align: right;">0.0481097</td>
</tr>
<tr class="odd">
<td style="text-align: left;">h</td>
<td style="text-align: right;">1598</td>
<td style="text-align: right;">0.0327983</td>
</tr>
<tr class="even">
<td style="text-align: left;">p</td>
<td style="text-align: right;">298</td>
<td style="text-align: right;">0.00611633</td>
</tr>
<tr class="odd">
<td style="text-align: left;">w</td>
<td style="text-align: right;">288</td>
<td style="text-align: right;">0.00591109</td>
</tr>
<tr class="even">
<td style="text-align: left;">u</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">0.00184721</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="10">
<div id="tbl-season" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="10">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-season-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: The distribution of the seasons of which mushrooms are present.
</figcaption>
<div aria-describedby="tbl-season-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<<<<<<< HEAD
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="10">
=======
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="52">
>>>>>>> main
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">season</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">a</td>
<td style="text-align: right;">24079</td>
<td style="text-align: right;">0.494212</td>
</tr>
<tr class="even">
<td style="text-align: left;">u</td>
<td style="text-align: right;">18300</td>
<td style="text-align: right;">0.3756</td>
</tr>
<tr class="odd">
<td style="text-align: left;">w</td>
<td style="text-align: right;">4149</td>
<td style="text-align: right;">0.0851566</td>
</tr>
<tr class="even">
<td style="text-align: left;">s</td>
<td style="text-align: right;">2194</td>
<td style="text-align: right;">0.045031</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="11">
<div id="tbl-columns-dropped" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="11">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-columns-dropped-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Features dropped from the original dataset prior to processing.
</figcaption>
<div aria-describedby="tbl-columns-dropped-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<<<<<<< HEAD
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="11">
=======
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="53">
>>>>>>> main
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">columns_to_drop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">cap-surface</td>
</tr>
<tr class="even">
<td style="text-align: left;">gill-attachment</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gill-spacing</td>
</tr>
<tr class="even">
<td style="text-align: left;">stem-root</td>
</tr>
<tr class="odd">
<td style="text-align: left;">stem-surface</td>
</tr>
<tr class="even">
<td style="text-align: left;">veil-type</td>
</tr>
<tr class="odd">
<td style="text-align: left;">veil-color</td>
</tr>
<tr class="even">
<td style="text-align: left;">spore-print-color</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Based on the Frequency and Percentage distributions, here are our findings:</p>
<ol type="1">
<li><p><a href="#tbl-cap-shape" class="quarto-xref">Table&nbsp;1</a>: The most common cap shape is <code>x</code> (convex), comprising 44.15% of the data. Other shapes like <code>f</code> (flat) and <code>s</code> (sunken) are also prevalent, while <code>c</code> (conical) is the least common with 2.98% appearance.</p></li>
<li><p><a href="#tbl-cap-color" class="quarto-xref">Table&nbsp;2</a>: The most frequently appeared color is <code>n</code> (brown), with 39.83% of the data. Other colors like <code>y</code> (yellow), <code>w</code> (white), and <code>g</code> (gray) are also well-represented, while rare colors like <code>b</code> (buff) and <code>l</code> (blue) appear in less than 2% of the data.</p></li>
<li><p><a href="#tbl-does-bruise-or-bleed" class="quarto-xref">Table&nbsp;3</a>: The majority of the mushrooms are <code>f</code> (do not bruise or bleed), while their counterpart makes up 17.22% of the data.</p></li>
<li><p><a href="#tbl-gill-color" class="quarto-xref">Table&nbsp;4</a>: The most common gill color is <code>w</code> (white), with 30.45% of the data. Other colors such as <code>n</code> (brown) and <code>y</code> (yellow) are also frequent, while rare gill colors like <code>e</code> (red), <code>b</code> (buff), and <code>u</code> (purple) appear in less than 2% of the data.</p></li>
<li><p><a href="#tbl-stem-color" class="quarto-xref">Table&nbsp;5</a>: <code>w</code> (white) and <code>n</code> (brown) are the dominating stem colors, accounting for 37.72% and 29.72% of the data, respectively. Other colors like <code>r</code> (green), <code>l</code> (blue), and <code>b</code> (buff) are less frequent, appearing in less than 1% of the observations.</p></li>
<li><p><a href="#tbl-has-ring" class="quarto-xref">Table&nbsp;6</a>: Most mushrooms are <code>f</code> (do not have a ring), with 74.90% observations. The remaining 25.10% mushrooms are <code>t</code> (have a ring).</p></li>
<li><p><a href="#tbl-ring-type" class="quarto-xref">Table&nbsp;7</a>: <code>f</code> (none) is the most common ring type, accounting for 82.28% of the data. Other types like <code>e</code> (evanescent) and <code>z</code> (zone) are less frequent, while rare types like <code>m</code> (movable) occur in less than 1% of the data.</p></li>
<li><p><a href="#tbl-habitat" class="quarto-xref">Table&nbsp;8</a>: The predominant habitat is <code>d</code> (woods), with 72.17% appearance. Other habitats such as <code>g</code> (grasses) and <code>l</code> (leaves) are less common, while <code>w</code> (waste), <code>p</code> (paths), and <code>u</code> (urban) only make up less than 1% of the data individually.</p></li>
<li><p><a href="#tbl-season" class="quarto-xref">Table&nbsp;9</a>: Most mushrooms grow in <code>a</code> (autumn), comprising 49.42% of the data, followed by <code>u</code> (summer) at 37.56%. The other two seasons <code>w</code> (winter) and <code>s</code> (spring) are less frequent.</p></li>
</ol>
<p>Categorical features will be encoded into binary format in the following preprocessing phase with <code>OneHotEncoder</code>. Since we are dealing with a mix of binary and non-binary categorical features, for features like <code>does-bruise-or-bleed</code> and <code>has-ring</code> that have two unique values, they will be handled with <code>drop='if_binary'</code> argument to reduce redundancy while still capturing the information.</p>
<p>It should be noted that many categorical features from the original dataset were dropped: See <a href="#tbl-columns-dropped" class="quarto-xref">Table&nbsp;10</a> for a full list. These features were found to have a substantial, and in some cases majority of entries missing. In this case, it appeared unreasonable to make assumptions about how to fill such entries without stronger domain-specific knowledge, so these features were dropped.</p>
</section>
<section id="part-4-the-distribution-of-the-target" class="level3">
<h3 class="anchored" data-anchor-id="part-4-the-distribution-of-the-target">Part 4: The distribution of the target</h3>
<div id="fig-target" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-target-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/target_variable_distribution.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-target-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: The Distribution of Feature Stem Color
</figcaption>
</figure>
</div>
<p>The target variable <code>class</code> represents whether a mushroom is <code>p</code> (poisonous) or <code>e</code> (edible). Understanding the distribution of the target helps assessing class balance, which might have impact on models’ performance.</p>
<p>Based on the Frequency and Percentage distribution <a href="#fig-target" class="quarto-xref">Figure&nbsp;4</a>, here are our findings:</p>
<ol type="1">
<li><p><code>p</code> (Poisonous): There are 26,996 instances of poisonous mushrooms, accounting for 55.41% of the data.</p></li>
<li><p><code>e</code> (Edible): There are 21,726 instances of edible mushrooms, constituting 44.59% of the data.</p></li>
</ol>
<p>Using <span class="math inline">\(F_{\beta}\)</span>, precision, recall, or confusion matrix to evaluate the model’s performance is advisable in the following procedure.</p>
</section>
</section>
<section id="result-discussion" class="level2">
<h2 class="anchored" data-anchor-id="result-discussion">Result &amp; Discussion</h2>
<section id="preprocessing-and-model-building" class="level3">
<h3 class="anchored" data-anchor-id="preprocessing-and-model-building">Preprocessing and Model Building</h3>
<p>Three classification models including Support Vector Classifier (SVC), K-Nearest Neighbors (KNN), and Logistic Regression are used to predict whether a mushroom is edible or poisonous. Predicting a mushroom to be edible when it is in fact poisonous could have severe health consequences. Therefore the best model should prioritize the minimization of this error. To do this, we can evaluate models on an <span class="math inline">\(F_{\beta}\)</span> score with <span class="math inline">\(\beta = 2\)</span>.</p>
<div class="cell" data-execution_count="14">
<div id="tbl-cv" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="14">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11: Cross-Validation Results by Model
</figcaption>
<div aria-describedby="tbl-cv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<<<<<<< HEAD
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="14">
=======
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="55">
>>>>>>> main
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">mean_test_accuracy</th>
<th style="text-align: right;">mean_test_f2_score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">KNN</td>
<td style="text-align: right;">0.930791</td>
<td style="text-align: right;">0.935691</td>
</tr>
<tr class="even">
<td style="text-align: left;">Logistic Regression</td>
<td style="text-align: right;">0.745495</td>
<td style="text-align: right;">0.77728</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SVC</td>
<td style="text-align: right;">0.996613</td>
<td style="text-align: right;">0.997111</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In <a href="#tbl-cv" class="quarto-xref">Table&nbsp;11</a>, we can see that after tuning the hyperparameter, the Logistic Regression model has the mean accuracy of 0.745 and mean <span class="math inline">\(F_{\beta}\)</span> score of 0.777 on the validation set. The KNN model has the mean accuracy of 0.931 and mean <span class="math inline">\(F_{\beta}\)</span> score of 0.936. The SVC outperforms both Logistic Regression and KNN significantly in both accuracy of 0.997 and <span class="math inline">\(F_{\beta}\)</span> score of 0.997. Thus, SVC is the ideal choice to identify edible or poisonous mushroom (recall is the highest priority), however it should be noted that this model takes extensive time to train. If faster training is preferred, the Logistic Regression model may be chosen as a suitable alternative due to comparable performance and a much faster fitting time.</p>
</section>
<section id="model-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="model-evaluation">Model Evaluation</h3>
<div class="cell" data-execution_count="15">
<div id="tbl-test-confusion-matrix" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="15">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-test-confusion-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12: Confusion matrix for the SVM model on test data.
</figcaption>
<div aria-describedby="tbl-test-confusion-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<<<<<<< HEAD
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="15">
=======
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="56">
>>>>>>> main
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Actual</th>
<th style="text-align: right;">e</th>
<th style="text-align: right;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">e</td>
<td style="text-align: right;">5430</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">p</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">6704</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The prediction model performed quite well on test data, with a final overall accuracy of 0.996 and <span class="math inline">\(F_{\beta}\)</span> score of 0.997 <a href="#tbl-test-confusion-matrix" class="quarto-xref">Table&nbsp;12</a>. The model only makes 47 mistakes out of 12181 test samples. 22 mistakes were predicting a poisonous mushroom as edible (false negative), while 25 mistakes were predicting a edible mushroom as poisonous (false positive). The model’s performance is promising for implementation, as false negatives represent potential safety risks and these errors could lead to consuming poisonous mushrooms, it is minimized to protect users. On the other hand, false positives are less harmful, they may lead to discarding safe mushrooms unnecessarily but do not endanger safety.</p>
<p>While the overall performance of the SVC model are impressive, efforts could focus on further reducing false negatives to enhance the safety of predictions. It might be important to take a closer look at the 47 misclassified observations to identify specific features contributing to these misclassifications. Implementing feature engineering on those features such as encoding rare categories differently can enhance the model’s power and reduce the misclassification cases. Additionally, trying other classifiers like Decision Tree and Random Forest which are less sensitive to scaling or irrelevant features might improve the prediction.</p>
</section>
<section id="limitation-and-future-work" class="level3">
<h3 class="anchored" data-anchor-id="limitation-and-future-work">Limitation and Future Work</h3>
<p>While the model yield promising performance, a key limitation is the lack of feature engineering based on domain-specific biological knowledge. There may be interactions between features or specific biological metrics with strong predictive power that were not considered. In future work, integrating such domain knowledge could enhance model performance and further reduce false negatives.</p>
<p>Additionally, the model still makes mistakes, including false positives and false negatives. Further investigation into the misclassified cases could help us identify patterns and feature interactions that the model failed to capture. These insights could make improvements in both feature engineering and model architecture.</p>
</section>
</section>
<section id="references" class="level2 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-niels_bantilan-proc-scipy-2020" class="csl-entry" role="listitem">
Bantilan, Niels. 2020. <em>Pandera: <span>S</span>tatistical <span>D</span>ata <span>V</span>alidation of <span>P</span>andas <span>D</span>ataframes</em>. Edited by Meghann Agarwal, Chris Calloway, Dillon Niederhut, and David Shupe. <a href="https://doi.org/ 10.25080/Majora-342d178e-010 ">https://doi.org/ 10.25080/Majora-342d178e-010 </a>.
</div>
<div id="ref-Chorev_Deepchecks_A_Library_2022" class="csl-entry" role="listitem">
Chorev, Shir, Philip Tannor, Dan Ben Israel, Noam Bressler, Itay Gabbay, Nir Hutnik, Jonatan Liberman, Matan Perlmutter, Yurii Romanyshyn, and Lior Rokach. 2022. <span>“<span class="nocase">Deepchecks: A Library for Testing and Validating Machine Learning Models and Data</span>.”</span> <em>Journal of Machine Learning Research</em> 23: 1–6. <a href="http://jmlr.org/papers/v23/22-0281.html">http://jmlr.org/papers/v23/22-0281.html</a>.
</div>
<div id="ref-cdc2024" class="csl-entry" role="listitem">
Disease Control, Centers for, and Prevention (CDC). 2024. <span>“Outbreak of Mushroom Poisoning Associated with Death Cap Mushrooms.”</span> <em>Morbidity and Mortality Weekly Report (MMWR)</em> 73 (10): 282–84. <a href="https://www.cdc.gov/mmwr/volumes/73/wr/mm7310a1.htm#suggestedcitation">https://www.cdc.gov/mmwr/volumes/73/wr/mm7310a1.htm#suggestedcitation</a>.
</div>
<div id="ref-harris2020array" class="csl-entry" role="listitem">
Harris, Charles R., K. Jarrod Millman, Stéfan J. van der Walt, Ralf Gommers, Pauli Virtanen, David Cournapeau, Eric Wieser, et al. 2020. <span>“Array Programming with <span>NumPy</span>.”</span> <em>Nature</em> 585 (7825): 357–62. <a href="https://doi.org/10.1038/s41586-020-2649-2">https://doi.org/10.1038/s41586-020-2649-2</a>.
</div>
<div id="ref-4160265" class="csl-entry" role="listitem">
Hunter, John D. 2007. <span>“Matplotlib: A 2D Graphics Environment.”</span> <em>Computing in Science &amp; Engineering</em> 9 (3): 90–95. <a href="https://doi.org/10.1109/MCSE.2007.55">https://doi.org/10.1109/MCSE.2007.55</a>.
</div>
<div id="ref-pytest8.3.4" class="csl-entry" role="listitem">
Krekel, Holger, Bruno Oliveira, Ronny Pfannschmidt, Floris Bruynooghe, Brianna Laugher, and Florian Bruhin. 2004. <em>Pytest 8.3.4</em>. <a href="https://github.com/pytest-dev/pytest">https://github.com/pytest-dev/pytest</a>.
</div>
<div id="ref-mckinney-proc-scipy-2010" class="csl-entry" role="listitem">
McKinney, Wes. 2010. <span>“<span>D</span>ata <span>S</span>tructures for <span>S</span>tatistical <span>C</span>omputing in <span>P</span>ython.”</span> In <em><span>P</span>roceedings of the 9th <span>P</span>ython in <span>S</span>cience <span>C</span>onference</em>, edited by Stéfan van der Walt and Jarrod Millman, 56–61. <a href="https://doi.org/ 10.25080/Majora-92bf1922-00a ">https://doi.org/ 10.25080/Majora-92bf1922-00a </a>.
</div>
<div id="ref-niosh2019" class="csl-entry" role="listitem">
Occupational Safety, National Institute for, and Health (NIOSH). 2019. <span>“Hazardous Mushroom Exposure: An Overlooked Concern in Agriculture and Forestry.”</span> <em>PubMed</em> 45: 31113097. <a href="https://pubmed.ncbi.nlm.nih.gov/31113097/">https://pubmed.ncbi.nlm.nih.gov/31113097/</a>.
</div>
<div id="ref-scikit-learn" class="csl-entry" role="listitem">
Pedregosa, F., G. Varoquaux, A. Gramfort, V. Michel, B. Thirion, O. Grisel, M. Blondel, et al. 2011. <span>“Scikit-Learn: Machine Learning in <span>P</span>ython.”</span> <em>Journal of Machine Learning Research</em> 12: 2825–30.
</div>
<div id="ref-Python" class="csl-entry" role="listitem">
Van Rossum, Guido, and Fred L. Drake. 2009. <em>Python 3 Reference Manual</em>. Scotts Valley, CA: CreateSpace.
</div>
<div id="ref-2020SciPy-NMeth" class="csl-entry" role="listitem">
Virtanen, Pauli, Ralf Gommers, Travis E. Oliphant, Matt Haberland, Tyler Reddy, David Cournapeau, Evgeni Burovski, et al. 2020. <span>“<span class="nocase"><span>SciPy</span> 1.0: Fundamental Algorithms for Scientific Computing in Python</span>.”</span> <em>Nature Methods</em> 17: 261–72. <a href="https://doi.org/10.1038/s41592-019-0686-2">https://doi.org/10.1038/s41592-019-0686-2</a>.
</div>
<div id="ref-secondary_mushroom_848" class="csl-entry" role="listitem">
Wagner, Heider, Dennis, and Georges Hattab. 2021. <span>“<span>Secondary Mushroom</span>.”</span> UCI Machine Learning Repository.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>