services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  bfrizzell/mushroom_classifier:7701e9f
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
